<html>
<head>
    <style>
        .container { display: flex; flex-direction: column; align-items: center;}
        .block { display: inline-block; vertical-align: top; text-align: left; }
        .block input { width: 150px; }
        .cell { width: 150px; display: inline-block; margin-bottom: 5px }
        .button { padding-left: 15px; color: black; text-decoration:none; font-size: 12px; border-radius: 10px;float: right; padding-right: 15px; }
    </style>
</head>
<body>
<div class="container">
<h2><?=$this->title;?></h2>
<?php
/** @var \App\Model\Eloquent\User $user */
$user = $this->user;
?>
Welcome! Please sign up <br> <br>
<? if(!$user): ?>
        <div class="block">
            <h2 style="text-align: center">Sign up</h2><br>
            <form action="/signin/signup" method="post">
                <div class="cell">Username:</div> <input type="text" value="" name="username"><br><br>
                <div class="cell">Email:</div> <input type="text" value="" name="email"><br><br>
                <div class="cell">Password:</div> <input type="text" value="" name="password"><br><br>
                <div class="cell">Repeat Password:</div> <input type="text" value="" name="password_2"><br><br>
                <input class="button" type="submit" value="Sign up"> <br><br>
            </form>
        </div>
    Already registered? Please sign in
    <a href="/signin">Sign In</a>

<? else: ?>
    You are signed in as <?=$user->getName();?>
<? endif; ?>
</div>
</body>
</head>
</html>